{ pkgs, ...}: {

environment.systemPackages = with pkgs; [
    cloudflare-warp
    libinput
    ntfs3g
    hyprland
    xdg-desktop-portal-hyprland
    waybar
    rofi
    git
    ghostty
    fish
    neovim
    neofetch
    fastfetch
    kitty
    brave	
    wget
    mlocate
    hyprpaper
    rustup
    gcc
    rsync 
    virt-manager 
    virt-viewer 
    virtualbox 
    colloid-gtk-theme 
    papirus-icon-theme 
    starship 
    pipes-rs 
    tmux 
    eza
    wl-clipboard
    hyprshot
    pamixer
    pavucontrol
    pipewire
    bibata-cursors
    font-awesome
    nerd-fonts.fira-code
    nerd-fonts.jetbrains-mono
    noto-fonts-cjk-sans
    noto-fonts-emoji-blob-bin
    noto-fonts
    wlogout
    blueman
    dunst
    discord
    obsidian
    spotify
    brightnessctl
    hyprlock
    docker 
    openvpn
    zed-editor
    python3Full
    python313Packages.pip
    unzip
    zip
    p7zip
    zig
  ];
}
