require("mini.cursorword").setup()
require("mini.pairs").setup()
require("mini.animate").setup()
require("mini.indentscope").setup()
require("mini.statusline").setup()
require("mini.comment").setup()
