paru -S hyprpaper reflector rsync virt-manager virt-viewer virtualbox ghostty neovim-nightly-bin colloid-gtk-theme-git papirus-icon-theme starship pipes-rs tmux exa ly wl-clipboard ttf-jetbrains-mono-nerd hyprshot pamixer pavucontrol pipewire ttf-font-awesome wlogout neovim fastfetch blueman dunst fish zen-browser discord code obsidian spotify brightnessctl hyprlock docker docker.socket openvpn locate waybar --needed

    hyprland
    xdg-desktop-portal-hyprland
    waybar
    rofi
    git
    ly
    ghostty
    fish
    neovim
    neofetch
    fastfetch
    kitty
    brave	
    wget
    locate
    hyprpaper
    reflector 
    rsync 
    virt-manager 
    virt-viewer 
    virtualbox 
    colloid-gtk-theme-git 
    papirus-icon-theme 
    starship 
    pipes-rs 
    tmux 
    exa
    wl-clipboard
    ttf-jetbrains-mono-nerd
    hyprshot
    pamixer
    pavucontrol
    pipewire
    ttf-font-awesome
    wlogout
    blueman
    dunst
    discordo
    bsidian
    spotify
    brightnessctl
    hyprlock
    docker
    docker.socket 
    openvpn
    zed
    zen
